-- MySQL Script generated by MySQL Workbench
-- jeu. 10 juin 2021 16:29:36 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frequentation_dtwh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frequentation_dtwh
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `frequentation_dtwh` DEFAULT CHARACTER SET utf8 ;
USE `frequentation_dtwh` ;

-- -----------------------------------------------------
-- Table `frequentation_dtwh`.`Dim_temporelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frequentation_dtwh`.`Dim_temporelle` ;

CREATE TABLE IF NOT EXISTS `frequentation_dtwh`.`Dim_temporelle` (
  `jour_id` INT NOT NULL AUTO_INCREMENT,
  `holidays_in` INT NULL,
  `holidays_ago` INT NULL,
  `pub_in` INT NULL,
  `pub_ago` INT NULL,
  `chretiennes_in` INT NULL,
  `chretiennes_ago` INT NULL,
  `musulmanes_in` INT NULL,
  `musulmanes_ago` INT NULL,
  `ramadan_in` INT NULL,
  `ramadan_ago` INT NULL,
  `juives_in` INT NULL,
  `juives_ago` INT NULL,
  PRIMARY KEY (`jour_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frequentation_dtwh`.`Dim_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frequentation_dtwh`.`Dim_site` ;

CREATE TABLE IF NOT EXISTS `frequentation_dtwh`.`Dim_site` (
  `site_id` INT NOT NULL AUTO_INCREMENT,
  `site_type` VARCHAR(5) NULL,
  `cantine_nom` VARCHAR(50) NULL,
  `annee_scolaire` VARCHAR(20) NULL,
  `effectif` INT NULL,
  `quartier_detail` VARCHAR(20) NULL,
  `prix_m2_appart` INT NULL,
  `prix_m2_maison` INT NULL,
  `prix_m2_quartier_detail_appart` INT NULL,
  `longitude` FLOAT NULL,
  `latitude` FLOAT NULL,
  PRIMARY KEY (`site_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frequentation_dtwh`.`Dim_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frequentation_dtwh`.`Dim_menu` ;

CREATE TABLE IF NOT EXISTS `frequentation_dtwh`.`Dim_menu` (
  `jour_id` INT NOT NULL AUTO_INCREMENT,
  `plats` VARCHAR(200) NULL,
  PRIMARY KEY (`jour_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frequentation_dtwh`.`Dim_evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frequentation_dtwh`.`Dim_evenement` ;

CREATE TABLE IF NOT EXISTS `frequentation_dtwh`.`Dim_evenement` (
  `jour_id` INT NOT NULL AUTO_INCREMENT,
  `chretiennes` TINYINT(1) NULL,
  `juives` TINYINT(1) NULL,
  `ramadan` TINYINT(1) NULL,
  `musulmanes` TINYINT(1) NULL,
  `greves` TINYINT(1) NULL,
  PRIMARY KEY (`jour_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frequentation_dtwh`.`Frequentation_quotidienne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frequentation_dtwh`.`Frequentation_quotidienne` ;

CREATE TABLE IF NOT EXISTS `frequentation_dtwh`.`Frequentation_quotidienne` (
  `jour_site_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `reel` INT NULL,
  `prevision` INT NULL,
  `jour_id` INT NOT NULL,
  `site_id` INT NOT NULL,
  PRIMARY KEY (`jour_site_id`, `jour_id`, `site_id`),
  INDEX `jour_id` (`jour_id` ASC),
  INDEX `site_id` (`site_id` ASC),
  CONSTRAINT `jour_id`
    FOREIGN KEY (`jour_id`)
    REFERENCES `frequentation_dtwh`.`Dim_temporelle` (`jour_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `site_id`
    FOREIGN KEY (`site_id`)
    REFERENCES `frequentation_dtwh`.`Dim_site` (`site_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Frequentation_quotidienne_Dim_menu1`
    FOREIGN KEY (`jour_id`)
    REFERENCES `frequentation_dtwh`.`Dim_menu` (`jour_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Frequentation_quotidienne_Dim_evenement1`
    FOREIGN KEY (`jour_id`)
    REFERENCES `frequentation_dtwh`.`Dim_evenement` (`jour_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
